### ISSUE TITLE
Nothing displayed with shaders

### ISSUE THREAD

**Issue by lostallmymoney** [kreezxil/Torch-Optimizer#5]
Title says it all

**Comment by kreezxil** [comment]
that's to be expected because that's what it modifies, the client side textures with an overlay. If the shaders you are using use the same method as I use then one will surely override the other.

However, thanks for your report and I have learned some things recently that might ensure that my mod gets run last after the shaders. I'll put out a release shortly to see if that solves the issue.

# ALSO

you left out the version of the mod you were using

**Comment by kreezxil** [comment]
Just to let you know, without knowing the version of the mod you were using, I will now have to compile for each branch of the mod. So don't be surprised if I don't release a version that you need right now.

**Comment by kreezxil** [comment]
Releasing a new version right now for 1.12.2. I didn't test before I started this.

But this is the screen shot using soartext fanver for 1.12.2 before TO is on.
![image](https://user-images.githubusercontent.com/3880072/74060675-1abeb900-49b0-11ea-940e-956260aad324.png)

and after TO is on
![image](https://user-images.githubusercontent.com/3880072/74060714-2d38f280-49b0-11ea-951c-05af1342f1a4.png)

What I did was add code that runs my mod at the lowest priority, this should allow your textures to render first before my numbers render.

**Comment by lostallmymoney** [comment]
Sorry about the version it was the last one on curseforge at the time good job on getting that fixed imma try it soon.

**Comment by kreezxil** [comment]
You still didn't tell me what version you were using. Saying it was the last one at the time is not helpful. Simply open the pack in your launcher and goto the mods section, scroll down to torch optimizer and there will be the version of the mod embedded in it's filename.
